#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3353C9CEF108B584 (mdroth@utexas.edu)
#
Name     : qemu
Version  : 3.1.0
Release  : 109
URL      : http://wiki.qemu-project.org/download/qemu-3.1.0.tar.xz
Source0  : http://wiki.qemu-project.org/download/qemu-3.1.0.tar.xz
Source99 : http://wiki.qemu-project.org/download/qemu-3.1.0.tar.xz.sig
Summary  : A lightweight multi-platform, multi-architecture disassembly framework
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 GPL-2.0+ GPL-3.0 LGPL-2.0+ LGPL-2.1 MIT
Requires: qemu-libexec = %{version}-%{release}
Requires: qemu-setuid = %{version}-%{release}
Requires: curl
Requires: libcap-ng
Requires: libiscsi
Requires: rdma-core
Requires: xfsprogs
BuildRequires : attr-dev
BuildRequires : automake-dev
BuildRequires : bison
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-qmake
BuildRequires : ceph-dev
BuildRequires : curl-dev
BuildRequires : flex
BuildRequires : glib
BuildRequires : glib-dev
BuildRequires : gnutls-dev
BuildRequires : gtk3
BuildRequires : gtk3-dev
BuildRequires : jemalloc
BuildRequires : jemalloc-dev
BuildRequires : libaio-dev
BuildRequires : libcap-dev
BuildRequires : libcap-ng
BuildRequires : libcap-ng-dev
BuildRequires : libiscsi
BuildRequires : libiscsi-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libseccomp-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : lzo-dev
BuildRequires : m4
BuildRequires : nfs-utils
BuildRequires : nfs-utils-dev
BuildRequires : numactl-dev
BuildRequires : rdma-core-dev
BuildRequires : snappy-dev
BuildRequires : spice
BuildRequires : spice-dev
BuildRequires : spice-protocol
BuildRequires : usbredir-dev
BuildRequires : util-linux-dev
BuildRequires : xfsprogs-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: configure.patch

%description
Capstone is a disassembly framework with the target of becoming the ultimate
disasm engine for binary analysis and reversing in the security community.

%package libexec
Summary: libexec components for the qemu package.
Group: Default

%description libexec
libexec components for the qemu package.


%package setuid
Summary: setuid components for the qemu package.
Group: Default

%description setuid
setuid components for the qemu package.


%prep
%setup -q -n qemu-3.1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547143473
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --prefix=/opt/qemu-ms/ \
--mandir=/opt/qemu-ms/man \
--datadir=/opt/qemu-ms/data \
--docdir=/opt/qemu-ms/doc \
--bindir=/opt/qemu-ms/bin \
--libdir=/opt/qemu-ms/lib \
--sysconfdir=/opt/qemu-ms/etc \
--localstatedir=/opt/qemu-ms/state \
--disable-sdl \
--disable-strip \
--enable-debug \
--python=/usr/bin/python \
--enable-gtk \
--enable-vnc \
--enable-kvm \
--target-list='x86_64-softmmu x86_64-linux-user' \
--enable-spice \
--enable-rbd \
--enable-attr \
--enable-cap-ng \
--enable-virtfs \
--enable-vhost-net \
--enable-usb-redir \
--enable-seccomp \
--enable-linux-aio \
--enable-tpm \
--enable-opengl \
--enable-libiscsi \
--enable-coroutine-pool \
--enable-jemalloc \
--enable-numa \
--enable-rdma \
--enable-modules \
--enable-vhdx
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export SOURCE_DATE_EPOCH=1547143473
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/opt/qemu-ms/bin/ivshmem-client
/opt/qemu-ms/bin/ivshmem-server
/opt/qemu-ms/bin/qemu-edid
/opt/qemu-ms/bin/qemu-ga
/opt/qemu-ms/bin/qemu-img
/opt/qemu-ms/bin/qemu-io
/opt/qemu-ms/bin/qemu-keymap
/opt/qemu-ms/bin/qemu-nbd
/opt/qemu-ms/bin/qemu-pr-helper
/opt/qemu-ms/bin/qemu-system-x86_64
/opt/qemu-ms/bin/qemu-x86_64
/opt/qemu-ms/bin/virtfs-proxy-helper
/opt/qemu-ms/data/qemu/QEMU,cgthree.bin
/opt/qemu-ms/data/qemu/QEMU,tcx.bin
/opt/qemu-ms/data/qemu/bamboo.dtb
/opt/qemu-ms/data/qemu/bios-256k.bin
/opt/qemu-ms/data/qemu/bios.bin
/opt/qemu-ms/data/qemu/canyonlands.dtb
/opt/qemu-ms/data/qemu/efi-e1000.rom
/opt/qemu-ms/data/qemu/efi-e1000e.rom
/opt/qemu-ms/data/qemu/efi-eepro100.rom
/opt/qemu-ms/data/qemu/efi-ne2k_pci.rom
/opt/qemu-ms/data/qemu/efi-pcnet.rom
/opt/qemu-ms/data/qemu/efi-rtl8139.rom
/opt/qemu-ms/data/qemu/efi-virtio.rom
/opt/qemu-ms/data/qemu/efi-vmxnet3.rom
/opt/qemu-ms/data/qemu/hppa-firmware.img
/opt/qemu-ms/data/qemu/keymaps/ar
/opt/qemu-ms/data/qemu/keymaps/bepo
/opt/qemu-ms/data/qemu/keymaps/common
/opt/qemu-ms/data/qemu/keymaps/cz
/opt/qemu-ms/data/qemu/keymaps/da
/opt/qemu-ms/data/qemu/keymaps/de
/opt/qemu-ms/data/qemu/keymaps/de-ch
/opt/qemu-ms/data/qemu/keymaps/en-gb
/opt/qemu-ms/data/qemu/keymaps/en-us
/opt/qemu-ms/data/qemu/keymaps/es
/opt/qemu-ms/data/qemu/keymaps/et
/opt/qemu-ms/data/qemu/keymaps/fi
/opt/qemu-ms/data/qemu/keymaps/fo
/opt/qemu-ms/data/qemu/keymaps/fr
/opt/qemu-ms/data/qemu/keymaps/fr-be
/opt/qemu-ms/data/qemu/keymaps/fr-ca
/opt/qemu-ms/data/qemu/keymaps/fr-ch
/opt/qemu-ms/data/qemu/keymaps/hr
/opt/qemu-ms/data/qemu/keymaps/hu
/opt/qemu-ms/data/qemu/keymaps/is
/opt/qemu-ms/data/qemu/keymaps/it
/opt/qemu-ms/data/qemu/keymaps/ja
/opt/qemu-ms/data/qemu/keymaps/lt
/opt/qemu-ms/data/qemu/keymaps/lv
/opt/qemu-ms/data/qemu/keymaps/mk
/opt/qemu-ms/data/qemu/keymaps/modifiers
/opt/qemu-ms/data/qemu/keymaps/nl
/opt/qemu-ms/data/qemu/keymaps/nl-be
/opt/qemu-ms/data/qemu/keymaps/no
/opt/qemu-ms/data/qemu/keymaps/pl
/opt/qemu-ms/data/qemu/keymaps/pt
/opt/qemu-ms/data/qemu/keymaps/pt-br
/opt/qemu-ms/data/qemu/keymaps/ru
/opt/qemu-ms/data/qemu/keymaps/sl
/opt/qemu-ms/data/qemu/keymaps/sv
/opt/qemu-ms/data/qemu/keymaps/th
/opt/qemu-ms/data/qemu/keymaps/tr
/opt/qemu-ms/data/qemu/kvmvapic.bin
/opt/qemu-ms/data/qemu/linuxboot.bin
/opt/qemu-ms/data/qemu/linuxboot_dma.bin
/opt/qemu-ms/data/qemu/multiboot.bin
/opt/qemu-ms/data/qemu/openbios-ppc
/opt/qemu-ms/data/qemu/openbios-sparc32
/opt/qemu-ms/data/qemu/openbios-sparc64
/opt/qemu-ms/data/qemu/palcode-clipper
/opt/qemu-ms/data/qemu/petalogix-ml605.dtb
/opt/qemu-ms/data/qemu/petalogix-s3adsp1800.dtb
/opt/qemu-ms/data/qemu/ppc_rom.bin
/opt/qemu-ms/data/qemu/pxe-e1000.rom
/opt/qemu-ms/data/qemu/pxe-eepro100.rom
/opt/qemu-ms/data/qemu/pxe-ne2k_pci.rom
/opt/qemu-ms/data/qemu/pxe-pcnet.rom
/opt/qemu-ms/data/qemu/pxe-rtl8139.rom
/opt/qemu-ms/data/qemu/pxe-virtio.rom
/opt/qemu-ms/data/qemu/qemu-icon.bmp
/opt/qemu-ms/data/qemu/qemu_logo_no_text.svg
/opt/qemu-ms/data/qemu/qemu_vga.ndrv
/opt/qemu-ms/data/qemu/s390-ccw.img
/opt/qemu-ms/data/qemu/s390-netboot.img
/opt/qemu-ms/data/qemu/sgabios.bin
/opt/qemu-ms/data/qemu/skiboot.lid
/opt/qemu-ms/data/qemu/slof.bin
/opt/qemu-ms/data/qemu/spapr-rtas.bin
/opt/qemu-ms/data/qemu/trace-events-all
/opt/qemu-ms/data/qemu/u-boot-sam460-20100605.bin
/opt/qemu-ms/data/qemu/u-boot.e500
/opt/qemu-ms/data/qemu/vgabios-bochs-display.bin
/opt/qemu-ms/data/qemu/vgabios-cirrus.bin
/opt/qemu-ms/data/qemu/vgabios-qxl.bin
/opt/qemu-ms/data/qemu/vgabios-ramfb.bin
/opt/qemu-ms/data/qemu/vgabios-stdvga.bin
/opt/qemu-ms/data/qemu/vgabios-virtio.bin
/opt/qemu-ms/data/qemu/vgabios-vmware.bin
/opt/qemu-ms/data/qemu/vgabios.bin
/opt/qemu-ms/lib/qemu/audio-oss.so
/opt/qemu-ms/lib/qemu/block-curl.so
/opt/qemu-ms/lib/qemu/block-iscsi.so
/opt/qemu-ms/lib/qemu/block-rbd.so
/opt/qemu-ms/lib/qemu/ui-gtk.so
/opt/qemu-ms/share/locale/bg/LC_MESSAGES/qemu.mo
/opt/qemu-ms/share/locale/de_DE/LC_MESSAGES/qemu.mo
/opt/qemu-ms/share/locale/fr_FR/LC_MESSAGES/qemu.mo
/opt/qemu-ms/share/locale/hu/LC_MESSAGES/qemu.mo
/opt/qemu-ms/share/locale/it/LC_MESSAGES/qemu.mo
/opt/qemu-ms/share/locale/tr/LC_MESSAGES/qemu.mo
/opt/qemu-ms/share/locale/zh_CN/LC_MESSAGES/qemu.mo

%files libexec
%defattr(-,root,root,-)
%exclude /usr/libexec/qemu-bridge-helper

%files setuid
%defattr(-,root,root,-)
%attr(4755, root, root) /usr/libexec/qemu-bridge-helper
